export const FETCH_CITY = 'FETCH_CITY'
export const FETCH_CITY_START = 'FETCH_CITY_START'
export const FETCH_CITY_SUCCESS = 'FETCH_CITY_SUCCESS'
export const FETCH_CITY_FAILED = 'FETCH_CITY_FAILED'

export const TOGGLE_CITY_SELECT= 'TOGGLE_CITY_SELECT'

export const REFRESH_SELECTED_START = 'REFRESH_SELECTED_START'
export const REFRESH_SELECTED_SUCCESS = 'REFRESH_SELECTED_SUCCESS'